### ISSUE TITLE
Failure parsing save at property section19SkipUsername

### ISSUE THREAD

**Issue by seth10** [bmaupin/react-civ5save#13]
#### Browser

Google Chrome
Version 79.0.3945.88 (Official Build) (64-bit)

#### Description

I uploaded `Pacal_0259 AD-1978.Civ5Save` from `‎⁨Macintosh HD⁩ ▸ ⁨Users⁩ ▸ ⁨seth ▸ ⁨Library⁩ ▸ ⁨Application Support⁩ ▸ ⁨Sid Meier's Civilization 5⁩ ▸ ⁨Saves⁩ ▸ ⁨single⁩` to https://bmaupin.github.io/civ5save-editor/ using the "Open save file" button and got the follow message:

``` 
The following error was encountered when trying to open the save file:
Failure parsing save at property section19SkipUsername
Please try another file or use the link on the left to report a bug.
```

#### Mods

Not mods, but DLC:

- Civ and Scenario Pack - Denmark Mac
- Civ and Scenario Pack - Mongols, Genghis Khan (Mac)
- Civ and Scenario Pack - Polynesia (Mac)
- Civ Pack - Babylon Nebuchadnezzar II (Mac)
- CIv V Digital Deluxe Content (Mac)
- Civilization V - Civ and Scenario Pack: Denmark (The V…
- Civilization V - Civ and Scenario Pack: Korea
- Civilization V - Civ and Scenario Pack: Polynesia
- Civilization V - Scenario Pack: Conquest of the New Wo…
- Civilization V - Scenario Pack: Wonders of the Ancient …
- Civilization V - Scrambled Continents Mac Pack
- Civilization V - Scrambled Nations Mac Pack
- Civilization V: Explorer's Map Pack Mac
- Civilization V: Gods & Kings Mac
- CivilizationV-DLC Ancient Wonders Mac
- CivilizationV-DLC Korea Mac
- Cradle of Civilization - Americas (Mac)
- Cradle of Civilization - Asia (Mac)
- Cradle of Civilization - Mediterranean (Mac)
- Cradle of Civilization - Mesopotamia (Mac)
- Double Civ and Scenario Pack - Spain, Isabella and Inc…
- Sid Meier's Civilization V: Brave New World
- Sid Meier's Civilization V: Gods and Kings

[Pacal_0259 AD-1978.Civ5Save.zip](https://github.com/bmaupin/civ5save-editor/files/3992728/Pacal_0259.AD-1978.Civ5Save.zip)

**Comment by seth10** [comment]
By the way, thank you for making this tool! The reason I'm trying to use it is because I accidentally clicked "Retire" early on, and I figured the "just...one..more..turn" would undo that, but now I have spaceship parts and can't launch them, realizing now that this is likely why. Is it even possible to edit the save to "undo" the retire?

**Comment by bmaupin** [comment]
I'll take a look when I get a chance although I'm not sure when that will be.

> Is it even possible to edit the save to "undo" the retire?

This may be possible although it's not currently supported. You can get a general idea of what's currently supported by clicking the *Demo* button.

My guess is that something like retiring would probably be stored in the compressed section of the file that can't be modified by this app. This app can modify anything in the uncompressed header of the file, but due to the complexity of the task I decided that modifying anything in the compressed portion was out of scope (see https://github.com/bmaupin/js-civ5save#non-goals).

I do have a few ideas:

- The easiest thing would be to see if you have an autosave from before you retired. It's been a while but I seem to recall that the game will automatically create saves for your last 10 turns. From the [manual](http://downloads.2kgames.com/civ5/site13/community/feature_manual/Civ_V_Manual_English_v1.0.pdf):

    > Auto-Save
    > The program automatically saves the game every turn. (You can alter the frequency of these
auto-saves in the Options screen.)

- There are some various mods that will let you do much more than this app will, such as the [Ingame Editor](https://steamcommunity.com/sharedfiles/filedetails/?id=77002777). I don't know much about them, though.

- You could ask on [https://forums.civfanatics.com/](https://forums.civfanatics.com/). The forums there are very active and if anyone would know how to fix this it'd be someone there.

- If none of that helps, I could look into this some more but I'd need some help from you. Basically I would need two different save files:
    - A save from a game where the Retire button hasn't been clicked (other than that it doesn't really matter)
    - Then I need a save from that exact same game after clicking the Retire button but without doing anything else

    With those two files I could do a quick comparison to see which part of the file the retirement status was stored in to see if it'd even be feasible to add it to this app.

Hope that helps!

**Comment by bmaupin** [comment]
I just submitted a fix for this issue, although as I mentioned I don't think it will help you undo the retire.

If you'd like me to look into it further feel free to reopen this issue.

Thanks!

**Comment by seth10** [comment]
Thank you so much for taking the time to fix this, and for providing those suggestions for my issue! Sorry I didn’t reply earlier, I was trying some methods and editors and haven’t gotten around to exhausting those options.

Unfortunately I don’t have an auto save from before retiring, that was way earlier in the game when I didn’t realize what I had done :( No matter though, one of my friends wants to play some multiplayer so we’re starting a new game. Again, thanks for your help and commitment to this app!
