### ISSUE TITLE
Failure parsing save at property section19Map

### ISSUE THREAD

**Issue by Aranel1500** [bmaupin/react-civ5save#15]
#### Browser
Safari
Version 13.0.3 (15608.3.10.1.4)

#### Description

It says: Failure parsing save at property section19Map
Amusingly, I can open all my multiplayer saves except the one I want to edit.
Thanks for the help

[ZigZag.Civ5.Save.zip](https://github.com/bmaupin/civ5save-editor/files/4020891/ZigZag.Civ5.Save.zip)

#### Mods

N/A

**Comment by Aranel1500** [comment]
I tried opening all the autosaves too, I can't do that either.

**Comment by bmaupin** [comment]
I'll take a look, thanks!

**Comment by bmaupin** [comment]
It looks like there was a new version for Mac released recently (Nov 2019) that has changed the build to `180925` (the version string is `1.0.3.279 (180925)`), which breaks most of the logic in this app. This is because the savegame format changes between Civ V versions, and the only reliable way of tracking this that I've found is the build number. However, this build number seems to be way out of order; the latest build version I have in my notes is build `403694`, which is from 2014.

Searching the web it seems that apparently it's also broken cross-platform multiplayer games:

https://www.google.com/search?q=civilization+v+%22180925%22

Could you check and see if there are any updates for Civ V (via Steam or however you play the game)? If so, please reopen the save in the latest version, save it to a new file, and try again.

If that doesn't work I think I might be able to hardcode a workaround for this build since `180925` is thankfully a really old build number (https://github.com/bmaupin/js-civ5save/blob/master/wiki/format.md#builds-and-versions).

Although I don't recommend it, if you're not using 10.15 (Catalina) then another possible workaround would be to install the legacy version of Civilization V by following the last step on this page:

https://support.2k.com/hc/articles/360011935293-Questions-Fr%C3%A9quemment-Pos%C3%A9es-sur-le-lancement-de-Civilization

And do the same thing (open the save and create a new one from it and try again).

**Comment by Aranel1500** [comment]
Thanks for the fast feedback, I've checked Steam and I am running the most up to date version of the game. I'm also running Catalina so I might be stuck on my current build, Catalina has been a disaster ever since I upgraded the os x. It's not that big of a deal, I guess I can just start a new game. My PC friends are gonna frustrated when they find out cross-platform play is botched though, hopefully, that will be fixed soon. At least you know about the issue now, so you can upgrade your app if you want :)

Thank you again for your help

**Comment by bmaupin** [comment]
From what little I've seen about this online, I don't get the sense that Aspyr (the developer of the Mac/Linux versions) is going to fix this:

> We do our best to provide the best gameplay experience on all platforms and given the option between retiring Sid Meier’s Civilization V on Mac or updating the game to 64-bit while disabling crossplay, we opted for the latter

https://steamcommunity.com/app/8930/discussions/1/1661194916748974393/?ctp=5

So I'll try to go ahead and hardcode a workaround for this. I'll hopefully have it ready in the next day or two.

Thanks!

**Comment by bmaupin** [comment]
I just submitted a fix; let me know if you still have problems. Thanks!
