### ISSUE TITLE
Encountering "Failure parsing save at property section19Map" on new save

### ISSUE THREAD

**Issue by Civ5Help** [bmaupin/react-civ5save#3]
I ran into this issue when running the editor on a recent save. It happens on every autosave that I have with the world aswell. The world is unmodded with all DLC enabled. I've attached the save for reference below.

[DJ HUGE.zip](https://github.com/bmaupin/civ5save-editor/files/1489895/DJ.HUGE.zip)

**Comment by bmaupin** [comment]
Interesting, it looks like your save file has an anomoly I've never seen before. I'm not sure if it's a corrupted file or if it's just an edge case that my code should cover. I'm hesitant to change the code just yet since I've examined dozens of save files and this is the first file I've seen with this particular issue.

I've edited the save file to "correct" the anomoly. Note that I haven't tested it to see if it will work in-game or not:
[~~DJ HUGE-corrected.zip~~](https://github.com/bmaupin/civ5save-editor/files/1497204/DJ.HUGE-corrected.zip) (see comments below)

If you have the time, I could use your help to investigate this further. Here's what would help me:

1. Can you confirm this is a multiplayer game, all victory conditions enabled, current turn is 329, max turns is 330?
2. Can you please open the corrected save file in the editor and let me know if you see anything that's incorrect?
3. Lastly, can you create a brand new save on your computer and see if it works in the editor? If not, please attach it here.

Thanks!

Technical details (for my own future reference):
[`section19Skip1`](https://github.com/bmaupin/js-civ5save/blob/master/src/Civ5SavePropertyDefinitions.json) appears to be shifted backward by 4 bytes (4 missing bytes before, 4 extra 00 bytes immediately after).

**Comment by Civ5Help** [comment]
1. Yes to all those questions
2. Everything looks right
3. After loading the modified save and saving again, I'm able to still open the file in the editor. If I make a new save, I'm also able to open it in the editor.

It may matter aswell, but Civ reports this save as having an "Unsupported number of players" (12 players on map set to Huge size. Quick combat is also on.

**Comment by bmaupin** [comment]
> Civ reports this save as having an "Unsupported number of players" (12 players on map set to Huge size

Did it always report that, or was it a result of the edit I made?

I chewed on this some more and I think it actually is something that needs to be fixed in the code. The save file I posted in my last comment may still work, but the changes I made could have unintended side effects.

If you do have any other save files from different games that exhibit the same problem, they'd be helpful in me getting this tested and fixed.

I'll keep you posted.

**Comment by bmaupin** [comment]
I just updated the app so hopefully your issue should be fixed. If it still gives you the same problem try doing a force refresh (Shift+F5 on Windows/Linux), closing your browser, clearing the cache, or try a different browser. If you still have issues let me know.

Thanks for reporting this!
