### ISSUE TITLE
Vox Populi: offset is outside the bounds of the DataView, Failure parsing save at property section30TxtKeyMapSize

### ISSUE THREAD

**Issue by Hello71** [bmaupin/react-civ5save#8]
#### Browser
Firefox 64.0

#### Description
a.Civ5Save: offset is outside the bounds of the DataView
b.Civ5Save: Failure parsing save at property section30TxtKeyMapSize

#### Mods

Vox Populi 12-18-1

[a.Civ5Save.gz](https://github.com/bmaupin/civ5save-editor/files/2730830/a.Civ5Save.gz)
[b.Civ5Save.gz](https://github.com/bmaupin/civ5save-editor/files/2730832/b.Civ5Save.gz)

**Comment by bmaupin** [comment]
Thanks for creating this issue! I'd love to help get it fixed, but I'm going to need some help from you.

Apparently Vox Populi (or at least the version you have installed) is actually made up of a collection of other mods:

(1) Community Patch
(2) Community Balance Overhaul
(3) City-State Diplomacy Mod for CBP
(4) C4DF - CBP
(5) More Luxuries - CBO Edition (5-14b)

So here's what I need from you:

1. Install each of these mods, *one at a time*
   I think you should be able to verify this by going to *Mods* in the game. It should show which mods are installed.
2. Start a new game and save it
3. Repeat for the next mod
4. When you're done you should have 5 new save games (one for each mod in the list above). Please attach them all to this issue

If you're like me and you'd like to know why, it's because one (or more) of these mods have made changes to the save files, which is why they won't work in my app. If I know which mod makes which changes, I can update my app to be able to handle those changes without breaking the app for everyone else.

**Comment by Hello71** [comment]
This is too much work for me, I just used IGE instead :)

If you really want to fix it I can still do it for you, but personally I don't really care anymore.

Also, FYI it also includes EUI ("UI_bc1"), but I think that (probably) shouldn't affect the save.

**Comment by bmaupin** [comment]
> This is too much work for me, I just used IGE instead :)

I don't blame you :)

> If you really want to fix it I can still do it for you, but personally I don't really care anymore.

Totally up to you. Considering Vox Populi seems to be the most popular mod these days, it'd be great to have. But I don't have time myself to create the saves so I understand if you don't either.

> Also, FYI it also includes EUI ("UI_bc1"), but I think that (probably) shouldn't affect the save.

Ah, okay. The list I got was directly from the mod section of the save file, but maybe I missed it or it only contains certain mods.

If nothing else, I made some improvements to the error output, so once I've integrated them into the app a.Civ5Save should generate a more helpful error. Since these are the first saves I've worked with that have mods, I also found where they're listed in the save file so I might try to add that to the app too if it's not too much effort.

Thanks!

**Comment by bmaupin** [comment]
... I think I'll go ahead and reopen this issue in case anyone else drops by who's able to create the save files I need.

**Comment by bmaupin** [comment]
(I'm posting some notes for my own future reference)

For both files:
- There appear to be ~8 extra bytes before [section29Timer1](https://github.com/bmaupin/js-civ5save/blob/master/src/Civ5SavePropertyDefinitions.js#L331)
- [section30Skip1](https://github.com/bmaupin/js-civ5save/blob/master/src/Civ5SavePropertyDefinitions.js#L447) also appears to have ~8 extra bytes
- ~~It's unclear where the extra bytes start and end, but it seems that they may be related as they both contain `59 00 00 00 EF BE AD DE 03` (`DEADBEEF` plus some extra stuff)~~ The extra bytes appear to be `59 00 00 00 EF BE AD DE`
- It seems like these extra bytes may be added by the Community Patch mod:
        - `EF BE AD DE`=[`DEADBEEF`](https://github.com/LoneGazebo/Community-Patch-DLL/blob/72137235dbab0c78d0c65a4b2ea33bad85b9ef61/CvGameCoreDLL_Expansion2/CustomMods.h#L1334)
        - `59 00 00 00`=89, as in [version 89](https://github.com/LoneGazebo/Community-Patch-DLL/blob/72137235dbab0c78d0c65a4b2ea33bad85b9ef61/CvGameCoreDLL_Expansion2/CustomMods.h#L26) (of the mod)

**Comment by Hello71** [comment]
I upgraded Vox Populi to version "1-19-1", started a new game with different parameters, and now get the error "Failure parsing save at property gameOptionsMap".
[AutoSave_Initial_0000 BC-4000.Civ5Save.gz](https://github.com/bmaupin/civ5save-editor/files/2825046/AutoSave_Initial_0000.BC-4000.Civ5Save.gz)

**Comment by Hello71** [comment]
I get the same error editing a non-initial save.

**Comment by bmaupin** [comment]
I spent a bit of time going through the SDK, game assets, and the source code for the mod and I think I figured out what's causing the issues. It seems like a reasonable goal for me to support the latest version, so hopefully I'll have a fix in place sometime by the end of the week.

Thanks!

**Comment by WardBenjamin** [comment]
Hello,

I'm still having this issue with the most recent version of Vox Populi and the hosted [editor](https://bmaupin.github.io/civ5save-editor/):

```
Failure parsing save at property section30TxtKeyMapSize
```

I've checked both a singleplayer file and a multiplayer file - let me know if I can help to debug this!

**Comment by bmaupin** [comment]
> Hello,
> 
> I'm still having this issue with the most recent version of Vox Populi and the hosted [editor](https://bmaupin.github.io/civ5save-editor/):
> 
> ```
> Failure parsing save at property section30TxtKeyMapSize
> ```
> 
> I've checked both a singleplayer file and a multiplayer file - let me know if I can help to debug this!

I can take a look. All I'll need is a save file from you to test with. You should be able to attach it directly to this issue, you'll just have to zip it first.

Also if you could let me know the exact version of Vox Populi you're using that woud be helpful.

Thanks!

**Comment by WardBenjamin** [comment]
Okay - here are the test save files (one singleplayer, one multiplayer):

[Multi_AutoSave_0059 BC-0640.zip](https://github.com/bmaupin/civ5save-editor/files/5983225/Multi_AutoSave_0059.BC-0640.zip)
[Single_Kamehameha_0175 AD-1750.zip](https://github.com/bmaupin/civ5save-editor/files/5983229/Single_Kamehameha_0175.AD-1750.zip)

I'm using Vox Populi version 12-1, installed as a modpack (DLC) from [here](https://forums.civfanatics.com/threads/dlc-modpack-repository.609278/page-41#post-15971708):
 - Community Patch v94
 - Community Balance Overhaul v13
 - City-State Diplomacy Mod for CBP v28
 - C3DF - CBP v11
 - More Luxuries - CBO Edition (5-14b) v155
 - Community Balance Overhaul - Compatability Files (EUI) v1
 - Promotion Icons for VP v3
 - UI - Promotion Tree for VP v22
 - Change VP Options v1

**Comment by bmaupin** [comment]
@WardBenjamin 

Thanks for that.

I'm not encountering a crash for the single player game. I also see that the list of mods is empty.

For the multiplayer game, I've investigated it, and the section of the file where mods are typically listed is empty. But I can see that the Community Patch mod has indeed modified the save file.

Unfortunately I don't think there's any way to fix this in the app. If the save file doesn't have the list of mods properly populated then there's no way for the app to apply any special behaviour needed for mods.

I have two ideas for why this may have happened:

1. Did you by any chance install the mod *after* the game was started? If so, that may be why it isn't registered in the list of mods.
1. If your answer is no, then my other idea is that maybe the mod isn't properly updating the list of mods in the save file. I saw the link you sent doesn't seem to be the official Vox Populi mod. You could either:
   - Try installing the official Vox Populi mod from here: https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/
   - Or contact the person who made the modified version of the mod and ask them to update it so it properly updates the list of mods in the save file

Hope that helps!

**Comment by WardBenjamin** [comment]
@bmaupin apologies - I should have been more clear. The "modpack" version of Vox Populi is loaded as a DLC instead of as a normal mod, so its components don't show up in the mod list (I assume this is by design). 

One way to make this work for the save editor is by catching this error and either automatically trying to load it again or prompting the user for a mod list (or a checkbox asking to confirm for at least the base Vox Populi pack). Do you think that might work?

**Comment by bmaupin** [comment]
Hmm, interesting. I have some ideas about how this could be done. What kind of properties are you looking to change in your save files? That might help give me an idea of how to approach this. Thanks!

**Comment by bmaupin** [comment]
I'll create a separate issue for this since the modpack version of Vox Populi is significantly different from the normal mod.

**Comment by bmaupin** [comment]
@WardBenjamin Since the modpack version of Vox Populi is significantly different from the normal mod, I've created a separate issue for this: #35. Unfortunately the modpack doesn't register itself properly as DLC either, so while it won't be impossible to get working, it will need to be a bit of a hack.
