### ISSUE TITLE
hi. 'Civilization V save editor' creator. im your big fan

### ISSUE THREAD

**Issue by wkdgytjr88** [bmaupin/react-civ5save#9]
Hi. thank you for read my writing.

first. Im south korean. sorry for my bad english. please understand me

i had moved to your change the civ5save web site.

it is my long time dream.

but im really want to change the file. more add AI players

I have civ5save cloud file. it file is have 22 player slot. it file is yet no start game. only waiting room.

i very really want to 43player slot waiting room file.

do you fix for me? please...

if you want my 22player slot waiting room file? i can send to you. give me your email address.

this is my email address ☞ wkdgytjr88@naver.com

thank you for read my writing. and im waiting for your answer!!

**Comment by bmaupin** [comment]
Hi!

The goal of this app is mostly changing game properties of games that have already been started, because before a game has been started there are a lot of properties that can be changed, but once it's been started there aren't very many.

Another issue is that the game itself has to support any changes you make to the save file. As far as I can tell, the game supports a maximum of 22 players, so increasing the number of players beyond that might not be supported by the game.

Since you haven't started your game yet, I think the best solution in your case would be to install a mod that would allow you to use 43 players, such as this one: https://steamcommunity.com/sharedfiles/filedetails/?id=159305629

I've also found the CivFanatics Forums to be very helpful for these kinds of questions: https://forums.civfanatics.com

Does that help?

**Comment by bmaupin** [comment]
Is there anything else I can help you with? If not I'll go ahead and close this issue.

Thanks!

**Comment by wkdgytjr88** [comment]
thank you for your mail!
 
im read your mail. and tried solve this problem.
 
but 43mod is only singleplay
 
so im give up this T.T
 
anyway very thank you your kindness
 
have a nice week!

**Comment by bmaupin** [comment]
I did a quick search of the CivFanatics Forums and found a few results, but I don't have much experience with mods so I'm not sure if they help you or not:

https://forums.civfanatics.com/threads/nmh-vp-43-civ-eui-more-mods.611034/
https://forums.civfanatics.com/threads/dlc-modpack-and-43-civ-version-repository.609278/
https://forums.civfanatics.com/threads/mpmpm-multiplayer-mod-dlc-hack-updated.533238/
https://forums.civfanatics.com/threads/43-civs-in-multiplayer.619166/

Since this isn't something my app can fix I'll go ahead and close this issue, but you're more than welcome to continue the conversation here if there's anything I can help with.

Thanks!
